// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppModuleScssNamespace {
  export interface IAppModuleScss {
    stylesHeader: string;
    stylesImage: string;
  }
}

declare const AppModuleScssModule: AppModuleScssNamespace.IAppModuleScss & {
  locals: AppModuleScssNamespace.IAppModuleScss;
};

export = AppModuleScssModule;
