// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AppModuleLessNamespace {
    export interface IAppModuleLess {
        stylesContainer: string;
    }
}

declare const AppModuleLessModule: AppModuleLessNamespace.IAppModuleLess & {
    locals: AppModuleLessNamespace.IAppModuleLess;
};

export = AppModuleLessModule;
